enabled: true

settings:
  world: "DeepSpace"
  teleport-command: "/teleport %x% %y% %z%"
  paste:
    # How many seconds delay between pasting a random
    # schematic? [Default: 10]
    delay-seconds: 10
    # The gap x gap area in which the main region will
    # be split and a schematic be pasted in.
    # A smaller gap value will result in denser pasting.
    # [Default: 150]
    gap: 150
  region:
    min-x: -10000
    max-x: 10000
    min-y: 0
    max-y: 220
    min-z: -10000
    max-z: 10000